version: '2'

services:

  broker1:
    image: confluentinc/cp-kafka:latest
    hostname: broker1
    container_name: broker1
    ports:
      - "9092:9092"
      - "9093:9093"
    #networks:
      #- confluent
    volumes:
      - /tmp/kraft/kraft-combined-logs-1:/etc/kafka/kraft-combined-logs-1:rw
      - ./clusterIdAssignor.sh:/tmp/clusterIdAssignor.sh
      - /tmp/kraft/cluster_id.txt:/tmp/cluster_id.txt:ro
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1    
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
      KAFKA_LOG_DIRS: /etc/kafka/kraft-combined-logs-1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    command: "bash -c 'if [ ! -f /tmp/clusterIdAssignor.sh ]; then echo \"ERROR: Did you forget the clusterIdAssignor.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/clusterIdAssignor.sh && /etc/confluent/docker/run ; fi'"